# Generated by Django 4.0.4 on 2022-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_calendly'),
    ]

    operations = [
        migrations.CreateModel(
            name='cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_id', models.CharField(max_length=256)),
            ],
        ),
    ]
