from django.db import models


# Create your models here.
class Account(models.Model):
    account_name = models.CharField(max_length=256, null=True, blank=True)
    followers_count = models.IntegerField(null=True, blank=True)
    time_of_list_gotted = models.DateTimeField(null=True, blank=True)

class FollowersList(models.Model):
    profile_id = models.CharField(max_length=256, null=True, blank=True)
    account = models.ForeignKey(Account,on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=256, null=True, blank=True)
    username = models.CharField(max_length=256, null=True, blank=True)
    created_at = models.CharField(max_length=256, null=True, blank=True)
    url_section_url = models.CharField(max_length=256, null=True, blank=True)
    description_section_url = models.CharField(max_length=256, null=True, blank=True)
    location = models.CharField(max_length=256, null=True, blank=True)
    description = models.TextField(max_length=700, null=True, blank=True)
    status = models.CharField(max_length=256, null=True, blank=True)
    status_count = models.CharField(max_length=256, null=True, blank=True)
    friends_count = models.CharField(max_length=256, null=True, blank=True)
    followers_count = models.CharField(max_length=256, null=True, blank=True)
    favourites_count = models.CharField(max_length=256, null=True, blank=True)
    blocked_by = models.BooleanField(max_length=256, null=True, blank=True)
    blocking = models.BooleanField(max_length=256, null=True, blank=True)
    contributors_enabled = models.BooleanField(max_length=256, null=True, blank=True)
    default_profile = models.BooleanField(max_length=256, null=True, blank=True)
    default_profile_image = models.BooleanField(max_length=256, null=True, blank=True)
    follow_request_sent = models.BooleanField(max_length=256, null=True, blank=True)
    following = models.BooleanField(max_length=256, null=True, blank=True)
    geo_enabled = models.BooleanField(max_length=256, null=True, blank=True)
    has_extended_profile = models.BooleanField(max_length=256, null=True, blank=True)
    profile_id_str = models.CharField(max_length=256, null=True, blank=True)
    is_translation_enabled = models.BooleanField(max_length=256, null=True, blank=True)
    is_translator = models.BooleanField(max_length=256, null=True, blank=True)
    listed_count = models.CharField(max_length=256, null=True, blank=True)
    live_following = models.BooleanField(max_length=256, null=True, blank=True)
    muting = models.BooleanField(max_length=256, null=True, blank=True)
    notification = models.BooleanField(max_length=256, null=True, blank=True)
    profile_background_color = models.CharField(max_length=256, null=True, blank=True)
    profile_background_image_url = models.CharField(max_length=256, null=True, blank=True)
    profile_background_image_url_https = models.CharField(max_length=256, null=True, blank=True)
    profile_background_title = models.BooleanField(max_length=256, null=True, blank=True)
    profile_image_url = models.CharField(max_length=256, null=True, blank=True)
    profile_image_url_https = models.CharField(max_length=256, null=True, blank=True)
    profile_link_color = models.CharField(max_length=256, null=True, blank=True)
    profile_slidebar_border_color = models.CharField(max_length=256, null=True, blank=True)
    profile_slidebar_fill_color = models.CharField(max_length=256, null=True, blank=True)
    profile_text_color = models.CharField(max_length=256, null=True, blank=True)
    profile_use_background_image = models.BooleanField(max_length=256, null=True, blank=True)
    protected = models.BooleanField(max_length=256, null=True, blank=True)
    traslator_type = models.CharField(max_length=256, null=True, blank=True)
    verified = models.BooleanField(max_length=256, null=True, blank=True)

class Compare(models.Model):
    follower = models.ForeignKey(FollowersList, null=True, blank=True,on_delete=models.CASCADE)
    calendly = models.BooleanField(null=True, blank=True)
    pipedrive = models.BooleanField( null=True, blank=True)
    streak = models.BooleanField( null=True, blank=True)
    leadfeeder = models.BooleanField(null=True, blank=True)

# class Calend(models.Model):
#     Profile_id = models.CharField(max_length=256, null=True, blank=True)
#     Name = models.CharField(max_length=256, null=True, blank=True)
#     Username = models.CharField(max_length=256, null=True, blank=True)
#     Created_at = models.CharField(max_length=256, null=True, blank=True)
#     Url_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Description_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Location = models.CharField(max_length=256, null=True, blank=True)
#     Description = models.TextField(max_length=700, null=True, blank=True)
#     Status = models.CharField(max_length=256, null=True, blank=True)
#     Status_count = models.CharField(max_length=256, null=True, blank=True)
#     Friends_count = models.CharField(max_length=256, null=True, blank=True)
#     Followers_count = models.CharField(max_length=256, null=True, blank=True)
#     Favourites_count = models.CharField(max_length=256, null=True, blank=True)
#     Blocked_by = models.BooleanField(max_length=256, null=True, blank=True)
#     Blocking = models.BooleanField(max_length=256, null=True, blank=True)
#     Contributors_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Follow_request_sent = models.BooleanField(max_length=256, null=True, blank=True)
#     Following = models.BooleanField(max_length=256, null=True, blank=True)
#     Geo_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Has_extended_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_id_str = models.CharField(max_length=256, null=True, blank=True)
#     Is_translation_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Is_translator = models.BooleanField(max_length=256, null=True, blank=True)
#     Listed_count = models.CharField(max_length=256, null=True, blank=True)
#     Live_following = models.BooleanField(max_length=256, null=True, blank=True)
#     Muting = models.BooleanField(max_length=256, null=True, blank=True)
#     Notification = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_background_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_title = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_link_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_border_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_fill_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_text_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_use_background_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Protected = models.BooleanField(max_length=256, null=True, blank=True)
#     Traslator_type = models.CharField(max_length=256, null=True, blank=True)
#     Verified = models.BooleanField(max_length=256, null=True, blank=True)

# class Calendly(models.Model):
#     Profile_id = models.CharField(max_length=256, null=True, blank=True)
#     Name = models.CharField(max_length=256, null=True, blank=True)
#     Username = models.CharField(max_length=256, null=True, blank=True)
#     Created_at = models.CharField(max_length=256, null=True, blank=True)
#     Url_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Description_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Location = models.CharField(max_length=256, null=True, blank=True)
#     Description = models.TextField(max_length=700, null=True, blank=True)
#     Status = models.CharField(max_length=256, null=True, blank=True)
#     Status_count = models.CharField(max_length=256, null=True, blank=True)
#     Friends_count = models.CharField(max_length=256, null=True, blank=True)
#     Followers_count = models.CharField(max_length=256, null=True, blank=True)
#     Favourites_count = models.CharField(max_length=256, null=True, blank=True)
#     Blocked_by = models.BooleanField(max_length=256, null=True, blank=True)
#     Blocking = models.BooleanField(max_length=256, null=True, blank=True)
#     Contributors_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Follow_request_sent = models.BooleanField(max_length=256, null=True, blank=True)
#     Following = models.BooleanField(max_length=256, null=True, blank=True)
#     Geo_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Has_extended_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_id_str = models.CharField(max_length=256, null=True, blank=True)
#     Is_translation_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Is_translator = models.BooleanField(max_length=256, null=True, blank=True)
#     Listed_count = models.CharField(max_length=256, null=True, blank=True)
#     Live_following = models.BooleanField(max_length=256, null=True, blank=True)
#     Muting = models.BooleanField(max_length=256, null=True, blank=True)
#     Notification = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_background_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_title = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_link_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_border_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_fill_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_text_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_use_background_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Protected = models.BooleanField(max_length=256, null=True, blank=True)
#     Traslator_type = models.CharField(max_length=256, null=True, blank=True)
#     Verified = models.BooleanField(max_length=256, null=True, blank=True)
# class Streak(models.Model):
#     Profile_id = models.CharField(max_length=256, null=True, blank=True)
#     Name = models.CharField(max_length=256, null=True, blank=True)
#     Username = models.CharField(max_length=256, null=True, blank=True)
#     Created_at = models.CharField(max_length=256, null=True, blank=True)
#     Url_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Description_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Location = models.CharField(max_length=256, null=True, blank=True)
#     Description = models.TextField(max_length=700, null=True, blank=True)
#     Status = models.CharField(max_length=256, null=True, blank=True)
#     Status_count = models.CharField(max_length=256, null=True, blank=True)
#     Friends_count = models.CharField(max_length=256, null=True, blank=True)
#     Followers_count = models.CharField(max_length=256, null=True, blank=True)
#     Favourites_count = models.CharField(max_length=256, null=True, blank=True)
#     Blocked_by = models.BooleanField(max_length=256, null=True, blank=True)
#     Blocking = models.BooleanField(max_length=256, null=True, blank=True)
#     Contributors_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Follow_request_sent = models.BooleanField(max_length=256, null=True, blank=True)
#     Following = models.BooleanField(max_length=256, null=True, blank=True)
#     Geo_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Has_extended_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_id_str = models.CharField(max_length=256, null=True, blank=True)
#     Is_translation_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Is_translator = models.BooleanField(max_length=256, null=True, blank=True)
#     Listed_count = models.CharField(max_length=256, null=True, blank=True)
#     Live_following = models.BooleanField(max_length=256, null=True, blank=True)
#     Muting = models.BooleanField(max_length=256, null=True, blank=True)
#     Notification = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_background_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_title = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_link_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_border_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_fill_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_text_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_use_background_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Protected = models.BooleanField(max_length=256, null=True, blank=True)
#     Traslator_type = models.CharField(max_length=256, null=True, blank=True)
#     Verified = models.BooleanField(max_length=256, null=True, blank=True)

# class Leadfeeder(models.Model):
#     Profile_id = models.CharField(max_length=256, null=True, blank=True)
#     Name = models.CharField(max_length=256, null=True, blank=True)
#     Username = models.CharField(max_length=256, null=True, blank=True)
#     Created_at = models.CharField(max_length=256, null=True, blank=True)
#     Url_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Description_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Location = models.CharField(max_length=256, null=True, blank=True)
#     Description = models.TextField(max_length=700, null=True, blank=True)
#     Status = models.CharField(max_length=256, null=True, blank=True)
#     Status_count = models.CharField(max_length=256, null=True, blank=True)
#     Friends_count = models.CharField(max_length=256, null=True, blank=True)
#     Followers_count = models.CharField(max_length=256, null=True, blank=True)
#     Favourites_count = models.CharField(max_length=256, null=True, blank=True)
#     Blocked_by = models.BooleanField(max_length=256, null=True, blank=True)
#     Blocking = models.BooleanField(max_length=256, null=True, blank=True)
#     Contributors_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Follow_request_sent = models.BooleanField(max_length=256, null=True, blank=True)
#     Following = models.BooleanField(max_length=256, null=True, blank=True)
#     Geo_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Has_extended_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_id_str = models.CharField(max_length=256, null=True, blank=True)
#     Is_translation_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Is_translator = models.BooleanField(max_length=256, null=True, blank=True)
#     Listed_count = models.CharField(max_length=256, null=True, blank=True)
#     Live_following = models.BooleanField(max_length=256, null=True, blank=True)
#     Muting = models.BooleanField(max_length=256, null=True, blank=True)
#     Notification = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_background_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_title = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_link_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_border_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_fill_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_text_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_use_background_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Protected = models.BooleanField(max_length=256, null=True, blank=True)
#     Traslator_type = models.CharField(max_length=256, null=True, blank=True)
#     Verified = models.BooleanField(max_length=256, null=True, blank=True)

# class pipedrive(models.Model):
#     Profile_id = models.CharField(max_length=256, null=True, blank=True)
#     Name = models.CharField(max_length=256, null=True, blank=True)
#     Username = models.CharField(max_length=256, null=True, blank=True)
#     Created_at = models.CharField(max_length=256, null=True, blank=True)
#     Url_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Description_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Location = models.CharField(max_length=256, null=True, blank=True)
#     Description = models.TextField(max_length=700, null=True, blank=True)
#     Status = models.CharField(max_length=256, null=True, blank=True)
#     Status_count = models.CharField(max_length=256, null=True, blank=True)
#     Friends_count = models.CharField(max_length=256, null=True, blank=True)
#     Followers_count = models.CharField(max_length=256, null=True, blank=True)
#     Favourites_count = models.CharField(max_length=256, null=True, blank=True)
#     Blocked_by = models.BooleanField(max_length=256, null=True, blank=True)
#     Blocking = models.BooleanField(max_length=256, null=True, blank=True)
#     Contributors_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Follow_request_sent = models.BooleanField(max_length=256, null=True, blank=True)
#     Following = models.BooleanField(max_length=256, null=True, blank=True)
#     Geo_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Has_extended_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_id_str = models.CharField(max_length=256, null=True, blank=True)
#     Is_translation_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Is_translator = models.BooleanField(max_length=256, null=True, blank=True)
#     Listed_count = models.CharField(max_length=256, null=True, blank=True)
#     Live_following = models.BooleanField(max_length=256, null=True, blank=True)
#     Muting = models.BooleanField(max_length=256, null=True, blank=True)
#     Notification = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_background_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_title = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_link_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_border_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_fill_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_text_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_use_background_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Protected = models.BooleanField(max_length=256, null=True, blank=True)
#     Traslator_type = models.CharField(max_length=256, null=True, blank=True)
#     Verified = models.BooleanField(max_length=256, null=True, blank=True)
#     def __str__(self):
#         return self.Description_section_url

# class calpipelead(models.Model):
#     Profile_id = models.CharField(max_length=256, null=True, blank=True)
#     Name = models.CharField(max_length=256, null=True, blank=True)
#     Username = models.CharField(max_length=256, null=True, blank=True)
#     Created_at = models.CharField(max_length=256, null=True, blank=True)
#     Url_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Description_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Location = models.CharField(max_length=256, null=True, blank=True)
#     Description = models.TextField(max_length=700, null=True, blank=True)
#     Status = models.CharField(max_length=256, null=True, blank=True)
#     Status_count = models.CharField(max_length=256, null=True, blank=True)
#     Friends_count = models.CharField(max_length=256, null=True, blank=True)
#     Followers_count = models.CharField(max_length=256, null=True, blank=True)
#     Favourites_count = models.CharField(max_length=256, null=True, blank=True)
#     Blocked_by = models.BooleanField(max_length=256, null=True, blank=True)
#     Blocking = models.BooleanField(max_length=256, null=True, blank=True)
#     Contributors_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Follow_request_sent = models.BooleanField(max_length=256, null=True, blank=True)
#     Following = models.BooleanField(max_length=256, null=True, blank=True)
#     Geo_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Has_extended_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_id_str = models.CharField(max_length=256, null=True, blank=True)
#     Is_translation_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Is_translator = models.BooleanField(max_length=256, null=True, blank=True)
#     Listed_count = models.CharField(max_length=256, null=True, blank=True)
#     Live_following = models.BooleanField(max_length=256, null=True, blank=True)
#     Muting = models.BooleanField(max_length=256, null=True, blank=True)
#     Notification = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_background_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_title = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_link_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_border_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_fill_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_text_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_use_background_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Protected = models.BooleanField(max_length=256, null=True, blank=True)
#     Traslator_type = models.CharField(max_length=256, null=True, blank=True)
#     Verified = models.BooleanField(max_length=256, null=True, blank=True)

# class calpipe(models.Model):
#     Profile_id = models.CharField(max_length=256, null=True, blank=True)
#     Name = models.CharField(max_length=256, null=True, blank=True)
#     Username = models.CharField(max_length=256, null=True, blank=True)
#     Created_at = models.CharField(max_length=256, null=True, blank=True)
#     Url_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Description_section_url = models.CharField(max_length=256, null=True, blank=True)
#     Location = models.CharField(max_length=256, null=True, blank=True)
#     Description = models.TextField(max_length=700, null=True, blank=True)
#     Status = models.CharField(max_length=256, null=True, blank=True)
#     Status_count = models.CharField(max_length=256, null=True, blank=True)
#     Friends_count = models.CharField(max_length=256, null=True, blank=True)
#     Followers_count = models.CharField(max_length=256, null=True, blank=True)
#     Favourites_count = models.CharField(max_length=256, null=True, blank=True)
#     Blocked_by = models.BooleanField(max_length=256, null=True, blank=True)
#     Blocking = models.BooleanField(max_length=256, null=True, blank=True)
#     Contributors_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Default_profile_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Follow_request_sent = models.BooleanField(max_length=256, null=True, blank=True)
#     Following = models.BooleanField(max_length=256, null=True, blank=True)
#     Geo_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Has_extended_profile = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_id_str = models.CharField(max_length=256, null=True, blank=True)
#     Is_translation_enabled = models.BooleanField(max_length=256, null=True, blank=True)
#     Is_translator = models.BooleanField(max_length=256, null=True, blank=True)
#     Listed_count = models.CharField(max_length=256, null=True, blank=True)
#     Live_following = models.BooleanField(max_length=256, null=True, blank=True)
#     Muting = models.BooleanField(max_length=256, null=True, blank=True)
#     Notification = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_background_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_background_title = models.BooleanField(max_length=256, null=True, blank=True)
#     Profile_image_url = models.CharField(max_length=256, null=True, blank=True)
#     Profile_image_url_https = models.CharField(max_length=256, null=True, blank=True)
#     Profile_link_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_border_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_slidebar_fill_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_text_color = models.CharField(max_length=256, null=True, blank=True)
#     Profile_use_background_image = models.BooleanField(max_length=256, null=True, blank=True)
#     Protected = models.BooleanField(max_length=256, null=True, blank=True)
#     Traslator_type = models.CharField(max_length=256, null=True, blank=True)
#     Verified = models.BooleanField(max_length=256, null=True, blank=True)

